import { AuthContext } from "@/Contexts/Auth";
import ConnectSection from "@/components/ConnectSection";
import FaqSection from "@/components/FaqSection";
import HeroSection from "@/components/HeroSection";
import WhySection from "@/components/WhySection";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useContext, useEffect } from "react";
import { toast } from "react-hot-toast";
import { NotificationManager } from "react-notifications";

export default function Home() {
  const router = useRouter();

  const { user } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Annadata.guru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-3">
        <div>
          <section id="HeroSection">
            {" "}
            <HeroSection />
          </section>
          <section id="ConnectSection">
            {" "}
            <ConnectSection />
          </section>
          <section id="WhySection">
            <WhySection />
          </section>

          <section id="FaqSection">
            <FaqSection />
          </section>
        </div>
      </main>
    </>
  );
}
