import { AuthContext } from "@/Contexts/Auth";
import { green } from "@/color";
import ListingComponents from "@/components/ListingComponents";
import axios from "axios";
import Head from "next/head";
import React, { useContext, useRef, useState } from "react";
import { toast } from "react-hot-toast";

const admin = () => {
  const emailRef = useRef();
  const passwordRef = useRef();
  const [tab, setTab] = useState("User Dashboard");
  const [err, setErr] = useState(false);

  const { admin, adminLogin, adminLogout } = useContext(AuthContext);

  const HandleSubmit = async (e) => {
    toast.loading("Fetching");
    e.preventDefault();
    if (passwordRef?.current?.value.length < 6) {
      setErr(true);
      toast.dismiss();
      toast.error("Enter Valid Password");
    } else {
      setErr(false);
      await axios
        .post("http://localhost:8000/api/adminLogin", {
          name: emailRef?.current?.value,
          nakedpassword: passwordRef?.current?.value,
        })
        .then((res) => {
          toast.dismiss();
          console.log(res);
          adminLogin({
            name: res.data.name,
            token: res.data.token,
          });
          toast.success("Login Successful");
        })
        .catch((err) => {
          adminLogout();
          if (err?.response?.status === 404) {
            toast.dismiss();
            toast.error(err?.response?.data?.message);
          } else if (err?.response?.status === 400) {
            toast.dismiss();

            toast.error(err?.response?.data?.message);
          }
        });
    }
  };
  console.log(tab);
  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {admin?.name ? (
          <>
            <div className="bg-[whitesmoke] px-2 pt-10  min-h-screen h-full w-full">
              <h1 className="text-gray-700 font-semibold pb-[0.5px]  text-center text-2xl">
                Admin Dashboard
              </h1>
              <div className="bg-blue-500  mb-4 mx-auto  h-1 w-20" />

              <div className="flex space-x-2 ">
                <div className="basis-1/5 h-[400px]  shadow-md bg-white">
                  <div className="p-1 flex flex-col space-y-2 italic">
                    <div className="py-2 border-black/30 border-b">
                      <h1 className="text-center font-semibold text-2xl  ">
                        Anndata.
                        <span className="text-[#39B54A] text-center w-full">
                          Guru
                        </span>
                      </h1>
                      <p className="text-center text-sm text-gray-500 italic">
                        Admin Menu
                      </p>
                    </div>
                    <div onClick={(e) => setTab("User Dashboard")}>
                      <p
                        className={` ${
                          tab === "User Dashboard" &&
                          "bg-green-500 shadow-md !text-white"
                        }  hover:bg-[#39B54A] py-2 text-center hover:text-white bg-[whitesmoke] text-black font-semibold rounded-md hover:shadow-md cursor-pointer`}
                      >
                        User Dashboard
                      </p>
                    </div>
                    <div onClick={(e) => setTab("Manage Meetings")}>
                      <p
                        className={` ${
                          tab === "Manage Meetings" &&
                          "bg-green-500 shadow-md !text-white"
                        }  hover:bg-[#39B54A] py-2 text-center hover:text-white bg-[whitesmoke] text-black font-semibold rounded-md hover:shadow-md cursor-pointer`}
                      >
                        Manage Meetings
                      </p>
                    </div>
                    <div onClick={(e) => setTab("Broadcast News")}>
                      <p
                        className={` ${
                          tab === "Broadcast News" &&
                          "bg-green-500 shadow-md !text-white"
                        }  hover:bg-[#39B54A] py-2 text-center hover:text-white bg-[whitesmoke] text-black font-semibold rounded-md hover:shadow-md cursor-pointer`}
                      >
                        Broadcast News
                      </p>
                    </div>
                    <div onClick={(e) => setTab("Match Users")}>
                      <p
                        className={` ${
                          tab === "Match Users" &&
                          "bg-green-500 shadow-md !text-white"
                        }  hover:bg-[#39B54A] py-2 text-center hover:text-white bg-[whitesmoke] text-black font-semibold rounded-md hover:shadow-md cursor-pointer`}
                      >
                        Match Users
                      </p>
                    </div>
                    <div onClick={(e) => setTab("Chats")}>
                      <p
                        className={` ${
                          tab === "Chats" &&
                          "bg-green-500 shadow-md !text-white"
                        }  hover:bg-[#39B54A] py-2 text-center hover:text-white bg-[whitesmoke] text-black font-semibold rounded-md hover:shadow-md cursor-pointer`}
                      >
                        Chats
                      </p>
                    </div>
                  </div>
                </div>
                <div className="basis-4/5 h-[800px] bg-white shadow-md rounded-md  ">
                  <div className="p-2">
                    <ListingComponents tab={tab} />
                  </div>
                </div>
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="bg-[whitesmoke] relative flex justify-center w-full h-screen">
              <div className="bg-green-500 h-[300px] w-full absolute opacity-80" />

              <div className="md:max-w-3xl m-auto z-[99] px-1  flex justify-center  w-full">
                <div className="bg-white  shadow-md flex w-full items-center flex-col justify-center py-4 rounded-md">
                  <div className="relative w-full h-full text-center">
                    <p className="font-semibold text-3xl tracking-wider">
                      {" "}
                      <img
                        src="/logo.png"
                        className="w-20 absolute md:-top-[65px] -top-[70px]  z-[99999] right-[50%] translate-x-[50%] md:translate-x-[0]  md:right-[330px]  bg-white rounded-full   h-20 mx-auto"
                        alt=""
                      />
                      Anndata.<span className="text-green-500">Guru</span>
                    </p>
                  </div>
                  <p className="text-gray-500 italic  ">
                    Admin Dashboard Login
                  </p>
                  <div>
                    <form
                      action=""
                      onSubmit={HandleSubmit}
                      className="flex flex-col space-y-3  my-4"
                    >
                      <div>
                        {" "}
                        <input
                          type="text"
                          ref={emailRef}
                          placeholder="Username"
                          className="border py-2 text-md px-2 shadow-md shadow-gray-100 border-black/30 focus:shadow-md placeholder:italic rounded-md placeholder:text-sm outline-none placeholder:text-center"
                        />
                      </div>
                      <div>
                        {" "}
                        <input
                          type="password"
                          ref={passwordRef}
                          placeholder="Password"
                          className={`border py-2 ${
                            err ? "border-red-500" : "border-black/30"
                          } text-md px-2 shadow-md shadow-gray-100  focus:shadow-md placeholder:italic rounded-md placeholder:text-sm outline-none placeholder:text-center`}
                        />
                        <p className="text-xs text-gray-500 italic mt-1">
                          Create new Admin ?{" "}
                          <span className="underline">
                            <a href="mailto:someone@example.com">
                              Contact Support
                            </a>
                          </span>
                        </p>
                      </div>

                      <div className="flex justify-center">
                        <button
                          type="submit"
                          className="bg-green-500 hover:bg-green-700 hover:scale-110 mt-1 transition-all duration-200 ease-in-out  px-8 py-1.5 text-white font-semibold shadow-md rounded-md "
                        >
                          Submit
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
};

export default admin;
